apiVersion: dapr.io/v1alpha1
kind: Component

metadata:
  name: statestore

spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: eric-dapr.redis.cache.windows.net:6380
  - name: redisPassword
    secretKeyRef:
      name: redis-password
      key:  redis-password
  - name: enableTLS
    value: true

auth:
  secretStore: secretstore