@web_HostAddress = http://localhost:5000

# dapr injected endpoint
GET {{web_HostAddress}}/dapr/subscribe

###

# dapr injected endpoint
POST {{web_HostAddress}}/test/sub
Content-Type: application/json

{
    "messageType": "test",
    "message": "fake messsage"
}

###

GET {{web_HostAddress}}/test/pub?text=hello+world1

###

GET {{web_HostAddress}}/test/config?key=name

###

GET {{web_HostAddress}}/test/crypto?text=my+secret+text

###

GET {{web_HostAddress}}/test/secret

###

GET {{web_HostAddress}}/test/state?key=string&value=string

###
